### ISSUE TITLE
Cannot read properties of undefined (reading 'hasOwnProperty').

### ISSUE THREAD

**Issue by AugustAohui** [TeamCodeStream/codestream-server#174]
I installed the program according to the provided README.md, however I found that the mongodb version does not seem to correspond to the latest code version. The version of mongodb in api_server/package.json does not support reconnectTries.
I tried to use the old npm package("mongodb": "3.5.2"), then execute: `source dev-env.sh`  & `npm run start:api`
report an error：

> bad schema property telemetry
TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')
    at StructuredConfigMongo._buildSection (/root/codestream-server/shared/codestream_configs/lib/structured_config_base.js:318:27)
    at StructuredConfigMongo._buildSection (/root/codestream-server/shared/codestream_configs/lib/structured_config_base.js:328:10)
    at StructuredConfigMongo.getSection (/root/codestream-server/shared/codestream_configs/lib/structured_config_base.js:348:8)
    at StructuredConfigMongo.getPreferredConfig (/root/codestream-server/shared/codestream_configs/lib/structured_config_base.js:123:27)
    at StructuredConfigMongo.loadConfig (/root/codestream-server/shared/codestream_configs/lib/structured_config_base.js:178:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async StructuredConfigMongo.loadPreferredConfig (/root/codestream-server/shared/codestream_configs/lib/structured_config_base.js:190:10)
    at async /root/codestream-server/api_server/bin/api_server.js:73:17

If you give me some to suggest I will be able to be very grateful!

**Comment by planteater** [comment]
@AugustAohui - Unfortunately CodeStream’s on-prem service was discontinued last summer.
