### ISSUE TITLE
Cannot send email using generic STMP

### ISSUE THREAD

**Issue by pepijnve** [TeamCodeStream/codestream-server#41]
At https://github.com/TeamCodeStream/codestream-server/blob/develop/shared/server_utils/smtp_email.js#L40 a read of `this.config.email.emailTo` is performed. The config that is passed to `SMTPEmail` at https://github.com/TeamCodeStream/codestream-server/blob/develop/outbound_email/src/emailSender.js#L13 is the `emailDeliveryService.NodeMailer` object though which does not have an `email` key. This results in the following error:

```
TypeError: Cannot read property 'emailTo' of undefined
    at SMTPEmail.sendEmail (/opt/mailout/codestream-server/shared/server_utils/smtp_email.js:40:25)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async EmailSender.sendSmtpEmail (/opt/mailout/codestream-server/outbound_email/src/emailSender.js:89:3)
    at async EmailSender.sendEmail (/opt/mailout/codestream-server/outbound_email/src/emailSender.js:30:11)
    at async InviteEmailHandler.sendEmail (/opt/mailout/codestream-server/outbound_email/src/emailHandler.js:74:4)
    at async InviteEmailHandler.handleMessage (/opt/mailout/codestream-server/outbound_email/src/emailHandler.js:17:4)
    at async OutboundEmailServer.processMessage (/opt/mailout/codestream-server/outbound_email/src/outboundEmailServer.js:178:3)
```

This seems to have been introduced by 2d99875d5e4ad668c185d2cb3f6458af546c89de.

**Comment by jimmyjayp** [comment]
I'd need to see the config that you're using to identify the problem.  Also, it might be useful to see the operational config (if you set the showConfig prop to true it will get dumped to the log.  Note that both these configs contain secret data so you may want to mask that before sending / posting.

**Comment by pepijnve** [comment]
Looking through the git history it seems like SMTPEmail initially received the entire config object tree. That commit I referenced changed that to only pass in the `NodeMailer` subtree. Seems like that debug block was not updated accordingly. Or I might just be misreading things of course 😄

I think these are the relevant bits you're looking for.

```
    "email": {
        "emailTo": null,
        "notificationInterval": 300000,
        "replyToDomain": "<redacted>",
        "senderEmail": "<redacted>",
        "supportEmail": "<redacted>",
        "suppressEmails": false
    },
    "emailDeliveryService": {
        "NodeMailer": {
            "host": "smtp-relay.gmail.com",
            "port": "587",
            "secure": true
        },
        "selected": "NodeMailer"
    },
```

**Comment by jimmyjayp** [comment]
Actually, I need to see the entire config.  I'm looking to see what setup the conditions for that code to get executed in the first place.

**Comment by pepijnve** [comment]
```
{
  "adminServer": {
    "adminServerDisabled": true
  },
  "apiServer": {
    "altBroadcasterHost": null,
    "authOrigin": "<redacted>",
    "autoMigrations": true,
    "callbackEnvironment": "onprem",
    "confirmCodeExpiration": 604800000,
    "confirmationExpiration": 86400000,
    "confirmationNotRequired": true,
    "cookieAuthenticatedPaths": [
      "^\\/c\\/",
      "^\\/r\\/",
      "^\\/web\\/"
    ],
    "disablePhoneHome": false,
    "dontWantAWS": true,
    "forgotPasswordExpiration": 86400000,
    "helpIsAvailable": false,
    "identityCookie": "tcs",
    "ignoreHttps": false,
    "ipc": {
      "broadcastServerId": "codestream_broadcaster_ipc_client",
      "clientId": "codestream_ipc_client",
      "serverId": "codestream_api_ipc_server"
    },
    "limits": {
      "maxMarkersPerRequest": 100,
      "maxPostsPerRequest": 100,
      "maxStreamsPerRequest": 100
    },
    "logger": {
      "basename": "api",
      "consoleOk": true,
      "debugOk": false,
      "directory": "undefined",
      "globalProperties": {
        "environment": "onprem",
        "service": "api"
      },
      "retentionPeriod": 2592000000
    },
    "marketingSiteUrl": "https://www.codestream.com",
    "mockMode": false,
    "optionalAuthenticatedPaths": [
      "^\\/help(\\/|$)",
      "^\\/c\\/",
      "^\\/p\\/",
      "^\\/r\\/",
      "^\\/web\\/"
    ],
    "phoneHomeUrl": "https://phone-home.codestream.com",
    "port": 443,
    "publicApiUrl": "<redacted>",
    "publicApiUrlParsed": {
      "host": "<redacted>",
      "port": 443,
      "secure": true
    },
    "requiresCsrfProtectionPaths": [
      "^\\/c\\/",
      "^\\/p\\/",
      "^\\/r\\/",
      "^\\/web\\/"
    ],
    "securePort": 12078,
    "sessionAwayTimeout": 600000,
    "showConfig": false,
    "signupTokenExpiration": 600000,
    "thirdPartyProviders": [
      "asana",
      "azuredevops",
      "bitbucket",
      "bitbucket_server",
      "github",
      "github_enterprise",
      "gitlab",
      "gitlab_enterprise",
      "jira",
      "jiraserver",
      "msteams",
      "slack",
      "trello",
      "youtrack",
      "okta",
      "clubhouse",
      "linear"
    ],
    "tmpDirectory": "undefined",
    "unauthenticatedPaths": [
      "^\\/no-auth\\/",
      "^\\/robots\\.txt$"
    ]
  },
  "broadcastEngine": {
    "codestreamBroadcaster": {
      "altApiHost": null,
      "history": {
        "retentionPeriod": 2592000000,
        "sweepPeriod": 3600000
      },
      "host": "<redacted>",
      "ignoreHttps": false,
      "logger": {
        "basename": "broadcaster",
        "consoleOk": true,
        "debugOk": false,
        "directory": "undefined",
        "retentionPeriod": 2592000000
      },
      "port": 12443,
      "secrets": {
        "api": "<redacted>",
        "auth": "<redacted>"
      },
      "securePort": 12075,
      "showConfig": false
    },
    "selected": "codestreamBroadcaster"
  },
  "email": {
    "emailTo": null,
    "notificationInterval": 300000,
    "replyToDomain": "<redacted>",
    "senderEmail": "<redacted>",
    "supportEmail": "<redacted>",
    "suppressEmails": false
  },
  "emailDeliveryService": {
    "NodeMailer": {
      "host": "smtp-relay.gmail.com",
      "port": "587",
      "secure": true
    },
    "selected": "NodeMailer"
  },
  "inboundEmailServer": {
    "inboundEmailDirectory": "undefined/mailq/new",
    "inboundEmailDisabled": true,
    "logger": {
      "basename": "inbound-email",
      "consoleOk": true,
      "debugOk": false,
      "directory": "undefined/log",
      "retentionPeriod": 2592000000
    },
    "processDirectory": "undefined/mailq/process",
    "showConfig": false,
    "tempAttachmentDirectory": "undefined/mailq/attachments",
    "tmpDirectory": "undefined/tmp"
  },
  "integrations": {
    "asana": {},
    "azuredevops": {},
    "bitbucket": {},
    "bitbucket_server": {
      "appClientId": "placeholder"
    },
    "clubhouse": {
      "appClientId": "placeholder"
    },
    "github": {},
    "github_enterprise": {
      "appClientId": "placeholder"
    },
    "gitlab": {},
    "gitlab_enterprise": {
      "appClientId": "placeholder"
    },
    "jira": {
      "appClientId": "<redacted>",
      "appClientSecret": "<redacted>"
    },
    "jiraserver": {
      "appClientId": "placeholder"
    },
    "linear": {},
    "msteams": {},
    "okta": {},
    "slack": {
      "appClientId": "<redacted>",
      "appClientSecret": "<redacted>",
      "appId": "<redacted>",
      "appSharingClientId": "<redacted>",
      "appSharingClientSecret": "<redacted>",
      "appSharingId": "<redacted>",
      "appSharingSigningSecret": "<redacted>",
      "appSigningSecret": "<redacted>",
      "appStrictClientId": "<redacted>",
      "appStrictClientSecret": "<redacted>",
      "appStrictId": "<redacted>",
      "appStrictSigningSecret": "<redacted>",
      "interactiveComponentsEnabled": false,
      "signingSecretsByAppIds": {
        "A01GQTX2H7Y": "<redacted>"
      }
    },
    "trello": {},
    "youtrack": {
      "appClientId": "placeholder"
    }
  },
  "outboundEmailServer": {
    "logger": {
      "basename": "outbound-email",
      "consoleOk": true,
      "debugOk": false,
      "directory": "/opt/mailout/log",
      "retentionPeriod": 2592000000
    },
    "maxPostsPerEmail": 25,
    "showConfig": true,
    "storage": {
      "mongo": {
        "database": "codestream",
        "url": "<redacted>"
      }
    },
    "tmpDirectory": "/opt/mailout/tmp"
  },
  "payments": {
    "discountPeriod": 604800000,
    "minPaidSeats": 1
  },
  "queuingEngine": {
    "rabbitmq": {
      "host": "<redacted>",
      "outboundEmailQueueName": "outboundEmail",
      "password": "stream",
      "port": 5672,
      "user": "code"
    },
    "selected": "rabbitmq"
  },
  "sharedGeneral": {
    "installationId": "923dd11d-530a-4475-81d2-62ba196749f3",
    "isOnPrem": true,
    "isProductionCloud": false,
    "runTimeEnvironment": "onprem"
  },
  "sharedSecrets": {
    "auth": "<redacted>",
    "confirmationCheat": "<redacted>",
    "cookie": "<redacted>",
    "mail": "<redacted>",
    "subscriptionCheat": "<redacted>",
    "telemetry": "<redacted>"
  },
  "ssl": {
    "cafile": "/opt/config/ca.crt",
    "certfile": "/opt/config/codestream.crt",
    "keyfile": "/opt/config/privkey.pem",
    "requireStrictSSL": false
  },
  "storage": {
    "mongo": {
      "database": "codestream",
      "hintsRequired": true,
      "queryLogging": {
        "disabled": false,
        "noLogData": [
          {
            "collection": "posts",
            "fields": [
              "text"
            ]
          },
          {
            "collection": "codemarks",
            "fields": [
              "text",
              "title"
            ]
          },
          {
            "collection": "markers",
            "fields": [
              "code"
            ]
          },
          {
            "collection": "users",
            "fields": [
              "providerInfo.*.*.accessToken",
              "providerInfo.*.*.refreshToken",
              "accessTokens.*.token",
              "pubNubToken",
              "broadcasterToken",
              "modifiedRepos",
              "compactModifiedRepos"
            ]
          },
          {
            "collection": "reviews",
            "fields": [
              "reviewChangesets",
              "reviewDiffs"
            ]
          }
        ]
      },
      "url": "<redacted>"
    }
  },
  "telemetry": {
    "segment": {
      "token": "<redacted>",
      "webToken": "<redacted>"
    }
  }
}
```

**Comment by jimmyjayp** [comment]
Fixed in this commit https://github.com/TeamCodeStream/codestream-server/commit/cc61764e4d3f33e135f3e946b9b590ddd5bca264 .  It's been merged into the develop branch so it's on its way to CI.  Will be out there with the next release.  Thank you for tracking down and reporting this!

**Comment by jimmyjayp** [comment]
Fixed in

**Comment by pepijnve** [comment]
Thanks for fixing this. Is there any way I can patch this into our local installation already? It's blocking my team from testing the product.

**Comment by planteater** [comment]
@pepijnve - We just did an on-prem release so if you update your instance you should be good to go.

https://docs.codestream.com/onprem/configs/single-host-linux/#update-your-system-to-the-latest-version

**Comment by pepijnve** [comment]
Excellent! I'll give it a try right away.
